<a href="https://colab.research.google.com/github/Shivam250124/Machine_Learning-/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

You are a data scientist / AI engineer at a meteorological consulting firm. You have been provided with a dataset named **"weather_data.csv"**, which includes detailed records of various weather conditions. The dataset comprises the following columns:

- **`hours_sunlight:`** The total number of hours of sunlight received in a day.
- **`humidity_level:`** The humidity level as a percentage.
- **`daily_temperature:`** The temperature recorded at the end of the day in degrees Celsius.

Your task is to use this dataset to build a linear regression model to predict the daily temperature based on the hours of sunlight and humidity level.

**Import Necessary Libraries**

In [1]:
#import necessary libraries

import numpy as np
import pandas as pd

### Task 1: Train a Linear Regression with Single Variable

1. Import the data from the "weather_data.csv" file and store it in a variable df.
2. Display the number of rows and columns in the dataset.
3. Display the first few rows of the dataset to get an overview.
4. Create a Linear Regression model and fit it using only the `hours_sunlight` variable to predict `daily_temperature`.
5. Print the model's coefficient and intercept.
6. Predict the daily temperature with the following hours of sunlight:
   - 5 hours
   - 8 hours
   - 12 hours

In [4]:
# Step 1: Import the data from the "weather_data.csv" file and store it in a variable 'df'
df=pd.read_csv("weather_data.csv")

# Step 2: Display the number of rows and columns in the dataset
df.shape[0]

# Step 3: Display the first few rows of the dataset to get an overview
df.head()

,hours_sunlight,humidity_level,daily_temperature
0,10.5,65,22.3
1,9.2,70,21.0
2,7.8,80,18.5
3,6.4,90,17.2
4,8.1,75,19.4


In [5]:
# Step 4: Create a Linear Regression model and fit it using only the 'hours_sunlight' variable to predict 'daily_temperature'
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df[["hours_sunlight"]],df["daily_temperature"])

LinearRegression()

In [6]:
# Step 5: Print the model's coefficient and intercept
model.coef_,model.intercept_

(array([1.36753934]), np.float64(8.533832092006133))

In [11]:
# Step 6: Predict the daily temperature for the following hours of sunlight: 5, 8, and 12
model.predict([[5]])
model.predict([[8]])
model.predict([[12]])

# Print the predicted temperatures


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.94430415])

In [12]:
test=pd.DataFrame([
    {"hours_sunlight":5},
    {"hours_sunlight":8},
    {"hours_sunlight":12}
])

In [13]:
model.predict(test)

array([15.37152878, 19.4741468 , 24.94430415])

### Task 2: Train a Linear Regression with Multiple Variable

- Create a Linear Regression model and fit it using both `hours_sunlight` and `humidity_level` variables to predict `daily_temperature`.
- Print the model's coefficients and intercept.
- Predict the daily temperature for the following conditions:
    - Hours of sunlight: 5 hours, Humidity level: 60%
    - Hours of sunlight: 8 hours, Humidity level: 75%
    - Hours of sunlight: 12 hours, Humidity level: 50%

In [17]:
#Step1: Create a Linear Regression model and fit it using both 'hours_sunlight' and 'humidity_level' variables to predict 'daily_temperature'
from sklearn.linear_model import LinearRegression
model1=LinearRegression()
model1.fit(df[["hours_sunlight","humidity_level"]],df["daily_temperature"])

LinearRegression()

In [18]:
#Step2: Print the model's coefficients and intercept
model1.coef_,model1.intercept_

(array([ 1.09803993, -0.05430624]), np.float64(14.833402427458843))

In [20]:
# Step3: Predict the daily temperature for the following conditions:
# Hours of sunlight: 5 hours, Humidity level: 60%
# Hours of sunlight: 8 hours, Humidity level: 75%
# Hours of sunlight: 12 hours, Humidity level: 50%

test1=pd.DataFrame([
    {"hours_sunlight":5,"humidity_level":60},
    {"hours_sunlight":8,"humidity_level":75},
    {"hours_sunlight":12,"humidity_level":50}
])

In [21]:
model1.predict(test1)

array([17.06522775, 19.54475397, 25.29456968])