<a href="https://colab.research.google.com/github/Shivam250124/Machine_Learning-/blob/main/Model_Evaluation_kfold_tutorial_synthetic_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h3 align="center">K Fold Cross Validation</h3>

We will generate a synthetic dataset

In [22]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_features=10,
    n_samples=1000,
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2,
    random_state=42
)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [23]:
from sklearn.metrics import classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.73      0.65      0.69       130
           1       0.66      0.74      0.70       120

    accuracy                           0.70       250
   macro avg       0.70      0.70      0.70       250
weighted avg       0.70      0.70      0.70       250



In [24]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, test_index in kf.split([50,60,70,80,90]):
    print(train_index, test_index)

[0 2 3 4] [1]
[0 1 2 3] [4]
[0 1 3 4] [2]
[1 2 3 4] [0]
[0 1 2 4] [3]


In [25]:
model = LogisticRegression()

for train_index, test_index in kf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model.fit(X_train, y_train)
    print(model.score(X_test, y_test))

0.675
0.715
0.72
0.645
0.72


### Cross validation on Logistic Regression

In [26]:
from sklearn.model_selection import cross_val_score

score_logistic=cross_val_score(LogisticRegression(), X, y, cv=kf, scoring="accuracy")#scoring="accuracy"/"roc_auc"
score_logistic

array([0.675, 0.715, 0.72 , 0.645, 0.72 ])

In [27]:
np.average(score_logistic)

np.float64(0.6950000000000001)

### Cross validation on Decision Tree

In [28]:
from sklearn.tree import DecisionTreeClassifier
score_decision_tree=cross_val_score(DecisionTreeClassifier(), X, y, cv=kf, scoring="")
score_decision_tree

array([0.725, 0.835, 0.765, 0.825, 0.8  ])

In [29]:
np.average(score_decision_tree)

np.float64(0.79)

### Cross validation on Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
score_random_forest=cross_val_score(RandomForestClassifier(n_estimators=10), X, y, cv=kf, scoring="accuracy")
score_random_forest

array([0.84 , 0.845, 0.865, 0.86 , 0.865])

In [31]:
np.average(score_random_forest)

np.float64(0.8549999999999999)

### Cross validation to evaluate same model with different parameters

Random Forest on 20 Trees

In [32]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(n_estimators=20), X, y, cv=kf, scoring="accuracy")

array([0.835, 0.905, 0.86 , 0.865, 0.89 ])

Random Forest on 30 Trees

In [33]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(n_estimators=30), X, y, cv=kf, scoring="accuracy")

array([0.89 , 0.92 , 0.875, 0.865, 0.89 ])

### Using cross_validate to evaluate multiple metrics

In [34]:
from sklearn.model_selection import cross_validate

cross_validate(LogisticRegression(), X, y, cv=kf, scoring=["accuracy", "roc_auc"])

{'fit_time': array([0.00808263, 0.00459242, 0.00419807, 0.0055058 , 0.00433707]),
 'score_time': array([0.00419188, 0.00374484, 0.00373912, 0.00408959, 0.00376415]),
 'test_accuracy': array([0.675, 0.715, 0.72 , 0.645, 0.72 ]),
 'test_roc_auc': array([0.7393617 , 0.77681072, 0.79251701, 0.74919872, 0.77569249])}